apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alerts
  namespace: monitoring
spec:
  groups:
    - name: example
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total{container!="",pod!=""}[5m])) by (namespace) > 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High CPU usage detected (mock)


