image:
  repository: nginx
  tag: latest

replicaCount: 1
fullnameOverride: chernous-fp-django

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/chernous_fp_devops/django
  tag: "1.0.0-mock"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

service:
  type: ClusterIP
  port: 80

env: {}

resources: {}

