apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
data:
{{- range $k, $v := .Values.env }}
  {{ $k }}: "{{ $v }}"
{{- end }}
  APP_NAME: "chernous_fp_devops"
  APP_ENV: "dev"


